version: "3.3"
services:
  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    networks:
      - flask_network

  proxy:
    build: proxy
    restart: always
    ports:
      - 8000:80
    networks:
      - flask_network

networks:
  flask_network: